project:
  type: book

book:
  title: "Differntial Gene Expression Modelling"
  author: "Muhammad Ilyas"
  description: "A thesis submitted in partial fulfillment for the degree of Master of science at The University of Exeter in 2023 in the Faculty of Environment, Science and Economy."
  chapters:
    - index.qmd
    - abstract.qmd
    - declaration.qmd
    - acknowledgements.qmd
    - "01-chap1.qmd"
    - "02-chap2.qmd"
  appendices:
    - "A-appA.qmd"
  references: refs.qmd
  page-footer:
    left: "Created using <a href='https://quarto.org'>Quarto</a>. © 2023, Muhammad Ilyas"
    border: false
    background: light
  sidebar:
    background: "#cccccc"
    style: "docked"

toc-title: "<b>Sections</b>"
html-math-method: katex
published-title: "Last updated"
date-format: "DD MMMM YYYY"
number-depth: 2
bibliography: thesisrefs.bib
csl: apa-single-spaced.csl
fig-height: 3.8
fig-width: 6.3
degreetype: Master of Science
submitted: 2023
affiliation: Faculty of Environment, Science and Economy
degrees: 'M.Sc., University of Exeter'
execute:
  freeze: auto
  echo: false

format:
  html:
    theme:
      - cosmo
      - thesis.scss
    fontsize: 16px
    mainfont: "Merriweather, Georgia, serif"
    code-link: true
  unimelbthesis-pdf:
    keep-tex: false
